// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CanvasLayer: typeof import('./src/components/CanvasLayer.vue')['default']
    DialogAppConfig: typeof import('./src/components/DialogAppConfig.vue')['default']
    DialogLayerConfig: typeof import('./src/components/DialogLayerConfig.vue')['default']
    DropDownApp: typeof import('./src/components/DropDownApp.vue')['default']
    DropDownFile: typeof import('./src/components/DropDownFile.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolbarButton: typeof import('./src/components/ToolbarButton.vue')['default']
    TopConfig: typeof import('./src/components/TopConfig.vue')['default']
  }
}
